### ISSUE TITLE
1.12.2 Glass shows missing texture

### ISSUE THREAD

**Issue by Astewen** [HenryLoenwind/TravelHut#5]
When using Travel Huts by itself, or with few mods, it works GREAT and I love it! However, with many mods I get a missing-texture (black/pink) for the hut glass in 1.12.2. It has to be a conflict, and I have looked inside the jar and don't see any obvious problems with blockstates or block assets. I've tried removing a bunch of possible mods, but cannot seem to track down which is causing the problem. Have you had any other reports? I'll continue to see if I can track down which mod(s) cause the conflict, but wondered if you can more strongly-bind the texture asset to the block? I'm new to mod development and don't understand how a conflict can upset your texture when you have the modID clearly set in the blockstates json. Weird.

**Comment by Astewen** [comment]
I took the time to create a new profile and go trough every mod I have (that I still use) and download the latest version along with the latest version of all dependencies. The problem did not recur so the conflict must be with an older version of some mod. If anyone else has this issue, update all your mods and the problem should go away.

Again Henry, I LOVE this mod - it makes it reasonable to get to those far-flung ice and mesa biomes when I need them!

**Comment by HenryLoenwind** [comment]
thx.

I also have no good idea how this can happen. My guess would be some mod that doesn't use the json system disturbing the texture loading...

**Comment by Astewen** [comment]
Henry, I finally tracked it down. The mod Pl3xStairs (v1.12.2-b18) is causing it. I have opened an issue with him and await a reply.

**Comment by HenryLoenwind** [comment]
can you please link that issue in here?

**Comment by Astewen** [comment]
I'm not sure if there's a GitHub facility for linking issues, but here is the issue I opened on Pl3x's mod:
[Stairs Mod causing missing texture in Travel Huts mod](https://github.com/BillyGalbreath/ForgeStairs/issues/3)

**Comment by Infinoid** [comment]
I'm having a similar problem in my own game.  In my case, the hatchery mod somehow causes travel hut glass textures to go missing.

You can reproduce the problem with an empty mods folder except for travelhut-3.0.1 and hatchery-1.12.2-2.1.2.

Related hatchery issue: https://github.com/GenDeathrow/Hatchery/issues/151

**Comment by HenryLoenwind** [comment]
Interesting. what are those people doing to the rendering? Travel Huts has no funky stuff at all, this is just a simple model ( https://github.com/HenryLoenwind/TravelHut/blob/1.12.2/src/main/resources/assets/travelhut/models/block/blockhutportalglass.json ) with a tint.

**Comment by GenDeathrow** [comment]
Well with both my mod and your mod, I'm missing my texture for liquid fertilizer fluid. Your's fails than mine fails in the logs... I post the logs up later. But its just a variants cant be found.  But even than I still don't see what the issue is right off the bat. Fluids are not my strong suit. But I'm not entirely sure why they are interacting like this. I'm tired and have been messing with this too long tonight. Hatchery was ported over and I'm sure I'm registering or doing something wrong.. but no time tonight to check into. But I don't remember this being an issue in 1.10 version... so possibly something when porting over?

**Comment by HenryLoenwind** [comment]
May be. If there's something in the logs, sure post them, I can look at it. I don't have the time to run a test setup right now, we released Ender IO yesterday and I'm drowning in users... ;)

**Comment by Infinoid** [comment]
There are exceptions loading model and loading blockstate, for travelhut portal glass and for hatchery liquid fertilizer, in the log.  Here they are.

[hatchery_travelhut_textures.log](https://github.com/HenryLoenwind/TravelHut/files/1871280/hatchery_travelhut_textures.log)

**Comment by HenryLoenwind** [comment]
From this log it looks like our CustomStateMapper got removed after we registered it. GenDeathrow, do you do anything with state mappers?

**Comment by Infinoid** [comment]
I also pulled in Pl3xStairs, just to see what happens.

Any of these mods, individually, seems to start up fine.  No model or blockstate loading errors.  Any combination of them results in model and blockstate loading errors.

**Comment by Infinoid** [comment]
Both hatchery and forgestairs (Pl3xStairs) call ModelLoader.setCustomStateMapper.

https://github.com/BillyGalbreath/ForgeStairs/blob/a0b902c0205b13edbe90827a5099bd3f2d538acd/src/main/java/net/pl3x/stairs/proxy/ClientProxy.java#L21

https://github.com/GenDeathrow/Hatchery/blob/953f2cf4566a54ef31cd733b163b2d6777f3c75d/src/main/java/com/gendeathrow/hatchery/core/proxies/ClientProxy.java#L187

**Comment by Infinoid** [comment]
I put a log message just above the setCustomStateMapper call in PortalGlassStateMapper.java.

`TravelHutMod.LOG.info("TravelHutMod.blockHutPortalGlass = " + TravelHutMod.blockHutPortalGlass);`

The output was:

`[10:16:16] [main/INFO] [travelhut]: TravelHutMod.blockHutPortalGlass = Block{null}`

Could it be a problem of registering the state mapper before the block itself was initialized?  (Sorry if it's a stupid question, I'm not good with java in general.)

**Comment by Infinoid** [comment]
I answered my own question with more log messages.  It is not an ordering issue.  Sorry for the noise.

**Comment by GenDeathrow** [comment]
Ok, I got it figured out. Basically what it is a load order thing, I think.. Hatchery has been using some old code for registering everything. Most things were switched over, but the model registering is not using the event. I switched it over and it works. 

Now I still don't completely get why just our blocks get messed up. But I switched over to using the ModelRegistryEvent and creating my state mapper at that point. Also switched over fluids registering my block/items over to using RegistryEvent.Register<Block>. And everything seems to work again. 

I'm guessing because we both registered in the proxies it was getting overridden or cleared out. No idea for sure. 


Edit: I need to change a few other things.. and will get an update pushed out next day or so.

**Comment by fivestang** [comment]
Hi,
I'm also getting missing textures with the following:
Forge 2768
Growthcraft CE v4.0.4.100
Travelhuts v3.0.1
It can be reproduced with those alone, removing Growthcraft causes textures to revert to normal.

(also reported [here](https://github.com/GrowthcraftCE/Growthcraft-1.12/issues/38#issue-371854859))

**Comment by HenryLoenwind** [comment]
Please retest with the latest version. If this works then Growthcraft better implement the same fixes, too.

**Comment by fivestang** [comment]
Ah, super, that fixes it!  Thank you!

**Comment by HenryLoenwind** [comment]
thanks for testing!
